/* 
Election Anomaly Analysis
Iva Cvetkovic
*/

const DATASETS = {"real": {"meta": {"label": "Real NJ public data (2020 General Election)", "year": 2020, "election": "U.S. President (General Election)", "sources": [{"title": "MIT Election Data and Science Lab (2022). \"U.S. President Precinct-Level Returns 2020\" (Harvard Dataverse, V4).", "url": "https://doi.org/10.7910/DVN/JXPREB"}, {"title": "NJ Division of Elections (2020). Official General Election Voter Turnout (County-level).", "url": "https://www.nj.gov/state/elections/assets/pdf/election-results/2020/2020-official-general-voter-turnout.pdf"}]}, "steps": [{"id": "turnout", "title": "County Turnout", "subtitle": "Top 10 counties by turnout rate (ballots cast / registered voters).", "unit": "%", "bars": [{"label": "Hunterdon", "value": 86.0}, {"label": "Monmouth", "value": 82.0}, {"label": "Gloucester", "value": 79.0}, {"label": "Burlington", "value": 78.0}, {"label": "Sussex", "value": 78.0}, {"label": "C.May", "value": 78.0}, {"label": "Ocean", "value": 78.0}, {"label": "Morris", "value": 78.0}, {"label": "Bergen", "value": 75.0}, {"label": "Somerset", "value": 74.0}], "kpis": {"Highest turnout": "Hunterdon (86.0%)", "Lowest among top 10": "Somerset (74.0%)"}, "summary": "Turnout rates come from an official NJ county-level turnout report. This view highlights which counties participated most (and least) relative to registered voters."}, {"id": "votes", "title": "County Vote Totals (Two-Party View)", "subtitle": "Top 10 counties by total votes (Dem + Republican) aggregated from the precinct results file.", "unit": "votes", "bars": [{"label": "Bergen", "value": 490384}, {"label": "Monmouth", "value": 373099}, {"label": "Middlesex", "value": 369717}, {"label": "Essex", "value": 342295}, {"label": "Ocean", "value": 337196}, {"label": "Morris", "value": 295015}, {"label": "Camden", "value": 261272}, {"label": "Burlington", "value": 257940}, {"label": "Union", "value": 250348}, {"label": "Hudson", "value": 247150}], "kpis": {"Most votes": "Bergen (490,384)", "10th place": "Hudson (247,150)"}, "summary": "This chart aggregates precinct-level results into county totals (two-party view) to compare how vote volume is distributed across New Jersey."}, {"id": "reject", "title": "Ballot Rejection Rate", "subtitle": "Top 10 counties by ballot rejection rate (rejected / cast).", "unit": "%", "bars": [{"label": "Middlesex", "value": 2.64}, {"label": "Union", "value": 2.62}, {"label": "Hudson", "value": 2.55}, {"label": "Warren", "value": 2.16}, {"label": "Salem", "value": 1.79}, {"label": "Monmouth", "value": 1.68}, {"label": "Cumberland", "value": 1.57}, {"label": "Somerset", "value": 1.5}, {"label": "Mercer", "value": 1.43}, {"label": "Ocean", "value": 1.42}], "kpis": {"Highest rejection rate": "Middlesex (2.64%)", "Lowest among top 10": "Ocean (1.42%)"}, "summary": "Rejection rate is not evidence of fraud by itself. This view is included as a quality/administration signal that can motivate follow-up questions."}], "benford_note": "Benford’s Law is disabled for the real dataset because public data availability and formatting do not support a reliable precinct-level first-digit test end-to-end in this application."}, "synthetic": {"meta": {"label": "Synthetic demo data (feature showcase)", "year": 2020, "election": "Demonstration only (not real results)", "sources": [{"title": "Synthetic data generated by this program to demonstrate the full analysis pipeline.", "url": ""}]}, "steps": [{"id": "turnout", "title": "County Turnout (Synthetic)", "subtitle": "Top 10 counties by turnout rate in the synthetic dataset.", "unit": "%", "bars": [{"label": "Passaic", "value": 73.3}, {"label": "Cumberland", "value": 73.0}, {"label": "Sussex", "value": 72.9}, {"label": "Monmouth", "value": 72.8}, {"label": "Warren", "value": 72.6}, {"label": "Camden", "value": 72.3}, {"label": "Atlantic", "value": 72.3}, {"label": "Morris", "value": 72.2}, {"label": "Bergen", "value": 72.2}, {"label": "Essex", "value": 72.0}], "kpis": {"Highest turnout": "Passaic (73.3%)", "Lowest among top 10": "Essex (72.0%)"}, "summary": "Synthetic mode contains intentionally injected anomalies so the detection pipeline has something to find and explain."}, {"id": "benford", "title": "Benford’s Law (Synthetic)", "subtitle": "Leading-digit frequencies computed from synthetic precinct vote totals.", "unit": "%", "bars": [{"label": "1", "value": 40.5}, {"label": "2", "value": 36.7}, {"label": "3", "value": 9.0}, {"label": "4", "value": 0.0}, {"label": "5", "value": 0.8}, {"label": "6", "value": 3.5}, {"label": "7", "value": 3.8}, {"label": "8", "value": 2.9}, {"label": "9", "value": 2.8}], "kpis": {"Most common digit": "Digit 1", "Least common digit": "Digit 4"}, "summary": "Benford’s Law can be explored only when precinct-level vote totals are available in a consistent form. Here it is used for demonstration."}, {"id": "outliers", "title": "Flagged Precincts (Synthetic)", "subtitle": "Top 10 precincts by Local Outlier Factor score (higher = more unusual.", "unit": "score", "bars": [{"label": "C.May 056", "value": 3.9}, {"label": "Salem 031", "value": 3.87}, {"label": "Bergen 034", "value": 3.57}, {"label": "Passaic 037", "value": 3.54}, {"label": "Sussex 015", "value": 3.52}, {"label": "Monmouth 023", "value": 3.47}, {"label": "Camden 040", "value": 3.37}, {"label": "Essex 015", "value": 3.36}, {"label": "Passaic 006", "value": 3.34}, {"label": "Ocean 011", "value": 3.33}], "kpis": {"Top score": "Cape May 056 (3.9)", "10th score": "Ocean 011 (3.33)"}, "summary": "This model uses turnout, vote share, and total votes (scaled) to flag unusual precinct patterns. Flags should be treated as prompts for investigation, not conclusions."}], "benford_note": ""}};
const SCAN_LINES_REAL = ["scan> Warren | ALLIANCE | votes=2 | precinct='BELVIDERE TOWN'", "scan> Salem | LIBERTARIAN | votes=17 | precinct='ALLOWAY TWP.'", "scan> Monmouth | ALLIANCE | votes=2 | precinct='AVON-BY-THE-SEA BORO'", "scan> Warren | UNITY AMERICA | votes=5 | precinct='ALPHA BORO'", "scan> Monmouth | UNITY AMERICA | votes=3 | precinct='ATLANTIC HIGHLANDS BOR'", "scan> Camden | DEMOCRAT | votes=2270 | precinct='BERLIN BOROUGH'", "scan> Ocean | SOCIALISM AND LIBERATION | votes=0 | precinct='BEACH HAVEN BORO'", "scan> Warren | LIBERTARIAN | votes=24 | precinct='BELVIDERE TOWN'", "scan> Bergen | GREEN | votes=12 | precinct='ALLENDALE BORO'", "scan> Burlington | LIBERTARIAN | votes=3 | precinct='BASS RIVER TWP'", "scan> Sussex | LIBERTARIAN | votes=3 | precinct='ANDOVER BORO'", "scan> Camden | GREEN | votes=26 | precinct='BELLMAWR BOROUGH'", "scan> Union | GREEN | votes=25 | precinct='BERKELEY HEIGHTS TWP.'", "scan> Atlantic | SOCIALISM AND LIBERATION | votes=27 | precinct='ATLANTIC CITY'", "scan> Ocean | LIBERTARIAN | votes=170 | precinct='BERKELEY TWP.'", "scan> Somerset | SOCIALISM AND LIBERATION | votes=3 | precinct='BEDMINSTER TWP.'", "scan> Monmouth | CONSTITUTION | votes=5 | precinct='ABERDEEN TWP'", "scan> Sussex | DEMOCRAT | votes=135 | precinct='ANDOVER BORO'", "scan> Somerset | LIBERTARIAN | votes=124 | precinct='BERNARDS TWP.'", "scan> Burlington | CONSTITUTION | votes=2 | precinct='BASS RIVER TWP'", "scan> Sussex | CONSTITUTION | votes=1 | precinct='ANDOVER TOWNSHIP'", "scan> Sussex | UNITY AMERICA | votes=4 | precinct='ANDOVER TOWNSHIP'", "scan> Hudson | LIBERTARIAN | votes=131 | precinct='BAYONNE CITY'", "scan> Ocean | SOCIALISM AND LIBERATION | votes=2 | precinct='BERKELEY TWP.'", "scan> Bergen | UNITY AMERICA | votes=1 | precinct='ALPINE BORO'", "scan> Camden | SOCIALISM AND LIBERATION | votes=4 | precinct='BERLIN TOWNSHIP'", "scan> Monmouth | CONSTITUTION | votes=0 | precinct='AVON-BY-THE-SEA BORO'", "scan> Monmouth | ALLIANCE | votes=0 | precinct='ASBURY PARK CITY'", "scan> Warren | LIBERTARIAN | votes=8 | precinct='ALPHA BORO'", "scan> Atlantic | DEMOCRAT | votes=9982 | precinct='ATLANTIC CITY'", "scan> Sussex | DEMOCRAT | votes=1424 | precinct='ANDOVER TOWNSHIP'", "scan> Atlantic | ALLIANCE | votes=1 | precinct='ABSECON CITY'", "scan> Cape May | GREEN | votes=0 | precinct='AVALON BORO'", "scan> Ocean | DEMOCRAT | votes=5804 | precinct='BARNEGAT TWP.'", "scan> Ocean | SOCIALISM AND LIBERATION | votes=1 | precinct='BARNEGAT TWP.'", "scan> Ocean | REPUBLICAN | votes=18146 | precinct='BERKELEY TWP.'", "scan> Monmouth | UNITY AMERICA | votes=14 | precinct='ABERDEEN TWP'", "scan> Monmouth | SOCIALISM AND LIBERATION | votes=0 | precinct='AVON-BY-THE-SEA BORO'", "scan> Monmouth | REPUBLICAN | votes=509 | precinct='ALLENTOWN BORO'", "scan> Camden | DEMOCRAT | votes=2419 | precinct='BARRINGTON BOROUGH'", "scan> Camden | UNITY AMERICA | votes=6 | precinct='BERLIN BOROUGH'", "scan> Camden | ALLIANCE | votes=3 | precinct='BELLMAWR BOROUGH'", "scan> Camden | DEMOCRAT | votes=1817 | precinct='BERLIN TOWNSHIP'", "scan> Monmouth | LIBERTARIAN | votes=33 | precinct='ATLANTIC HIGHLANDS BOR'", "scan> Monmouth | GREEN | votes=29 | precinct='ASBURY PARK CITY'", "scan> Ocean | REPUBLICAN | votes=422 | precinct='BEACH HAVEN BORO'", "scan> Cape May | UNITY AMERICA | votes=0 | precinct='AVALON BORO'", "scan> Ocean | CONSTITUTION | votes=9 | precinct='BARNEGAT TWP.'", "scan> Salem | SOCIALISM AND LIBERATION | votes=1 | precinct='ALLOWAY TWP.'", "scan> Hudson | REPUBLICAN | votes=10869 | precinct='BAYONNE CITY'", "scan> Hunterdon | UNITY AMERICA | votes=2 | precinct='ALEXANDRIA TWP'", "scan> Monmouth | CONSTITUTION | votes=3 | precinct='BELMAR BORO'", "scan> Warren | ALLIANCE | votes=0 | precinct='ALPHA BORO'", "scan> Camden | LIBERTARIAN | votes=24 | precinct='BERLIN TOWNSHIP'", "scan> Ocean | ALLIANCE | votes=14 | precinct='BERKELEY TWP.'", "scan> Camden | UNITY AMERICA | votes=2 | precinct='BARRINGTON BOROUGH'", "scan> Essex | ALLIANCE | votes=15 | precinct='BELLEVILLE'", "scan> Bergen | UNITY AMERICA | votes=3 | precinct='BERGENFIELD BORO'", "scan> Somerset | LIBERTARIAN | votes=52 | precinct='BEDMINSTER TWP.'", "scan> Camden | CONSTITUTION | votes=7 | precinct='BARRINGTON BOROUGH'", "scan> Hunterdon | ALLIANCE | votes=2 | precinct='ALEXANDRIA TWP'", "scan> Essex | REPUBLICAN | votes=5977 | precinct='BELLEVILLE'", "scan> Union | DEMOCRAT | votes=4688 | precinct='BERKELEY HEIGHTS TWP.'", "scan> Monmouth | ALLIANCE | votes=2 | precinct='BELMAR BORO'", "scan> Camden | SOCIALISM AND LIBERATION | votes=1 | precinct='AUDUBON PARK BOROUGH'", "scan> Bergen | ALLIANCE | votes=4 | precinct='BERGENFIELD BORO'", "scan> Ocean | SOCIALISM AND LIBERATION | votes=0 | precinct='BAY HEAD BORO'", "scan> Sussex | ALLIANCE | votes=2 | precinct='ANDOVER TOWNSHIP'", "scan> Monmouth | ALLIANCE | votes=2 | precinct='ATLANTIC HIGHLANDS BOR'", "scan> Sussex | ALLIANCE | votes=0 | precinct='ANDOVER BORO'", "scan> Camden | REPUBLICAN | votes=2214 | precinct='BERLIN BOROUGH'", "scan> Warren | DEMOCRAT | votes=559 | precinct='BELVIDERE TOWN'", "scan> Atlantic | REPUBLICAN | votes=2879 | precinct='ATLANTIC CITY'", "scan> Camden | SOCIALISM AND LIBERATION | votes=2 | precinct='BARRINGTON BOROUGH'", "scan> Sussex | SOCIALISM AND LIBERATION | votes=1 | precinct='ANDOVER BORO'", "scan> Somerset | ALLIANCE | votes=1 | precinct='BEDMINSTER TWP.'", "scan> Warren | DEMOCRAT | votes=1470 | precinct='ALLAMUCHY TWP.'", "scan> Camden | ALLIANCE | votes=1 | precinct='AUDUBON BOROUGH'", "scan> Salem | ALLIANCE | votes=0 | precinct='ALLOWAY TWP.'", "scan> Monmouth | SOCIALISM AND LIBERATION | votes=1 | precinct='BELMAR BORO'", "scan> Bergen | ALLIANCE | votes=1 | precinct='ALPINE BORO'", "scan> Monmouth | CONSTITUTION | votes=0 | precinct='ASBURY PARK CITY'", "scan> Monmouth | UNITY AMERICA | votes=1 | precinct='ALLENTOWN BORO'", "scan> Camden | GREEN | votes=23 | precinct='AUDUBON BOROUGH'", "scan> Burlington | ALLIANCE | votes=0 | precinct='BASS RIVER TWP'", "scan> Bergen | CONSTITUTION | votes=14 | precinct='BERGENFIELD BORO'", "scan> Salem | GREEN | votes=5 | precinct='ALLOWAY TWP.'", "scan> Burlington | DEMOCRAT | votes=213 | precinct='BASS RIVER TWP'", "scan> Hudson | GREEN | votes=87 | precinct='BAYONNE CITY'", "scan> Warren | GREEN | votes=4 | precinct='ALPHA BORO'", "scan> Bergen | SOCIALISM AND LIBERATION | votes=2 | precinct='ALLENDALE BORO'", "scan> Monmouth | DEMOCRAT | votes=122 | precinct='ALLENHURST BORO'", "scan> Monmouth | LIBERTARIAN | votes=4 | precinct='AVON-BY-THE-SEA BORO'", "scan> Atlantic | CONSTITUTION | votes=9 | precinct='ABSECON CITY'", "scan> Essex | SOCIALISM AND LIBERATION | votes=13 | precinct='BELLEVILLE'", "scan> Camden | UNITY AMERICA | votes=4 | precinct='BELLMAWR BOROUGH'", "scan> Ocean | ALLIANCE | votes=0 | precinct='BEACH HAVEN BORO'", "scan> Ocean | LIBERTARIAN | votes=2 | precinct='BARNEGAT LIGHT BORO'", "scan> Camden | REPUBLICAN | votes=2851 | precinct='BELLMAWR BOROUGH'", "scan> Monmouth | UNITY AMERICA | votes=5 | precinct='ASBURY PARK CITY'", "scan> Ocean | DEMOCRAT | votes=327 | precinct='BAY HEAD BORO'", "scan> Monmouth | ALLIANCE | votes=0 | precinct='ALLENHURST BORO'", "scan> Monmouth | GREEN | votes=24 | precinct='BELMAR BORO'", "scan> Monmouth | CONSTITUTION | votes=4 | precinct='ATLANTIC HIGHLANDS BOR'", "scan> Monmouth | DEMOCRAT | votes=1716 | precinct='BELMAR BORO'", "scan> Camden | LIBERTARIAN | votes=4 | precinct='AUDUBON PARK BOROUGH'", "scan> Camden | ALLIANCE | votes=4 | precinct='BERLIN TOWNSHIP'", "scan> Camden | DEMOCRAT | votes=336 | precinct='AUDUBON PARK BOROUGH'", "scan> Camden | ALLIANCE | votes=2 | precinct='BERLIN BOROUGH'", "scan> Atlantic | REPUBLICAN | votes=2675 | precinct='ABSECON CITY'", "scan> Monmouth | REPUBLICAN | votes=5021 | precinct='ABERDEEN TWP'", "scan> Ocean | DEMOCRAT | votes=9976 | precinct='BERKELEY TWP.'", "scan> Cape May | CONSTITUTION | votes=0 | precinct='AVALON BORO'", "scan> Hudson | ALLIANCE | votes=10 | precinct='BAYONNE CITY'", "scan> Ocean | LIBERTARIAN | votes=105 | precinct='BARNEGAT TWP.'", "scan> Hudson | UNITY AMERICA | votes=23 | precinct='BAYONNE CITY'", "scan> Sussex | LIBERTARIAN | votes=41 | precinct='ANDOVER TOWNSHIP'", "scan> Union | CONSTITUTION | votes=6 | precinct='BERKELEY HEIGHTS TWP.'", "scan> Monmouth | LIBERTARIAN | votes=41 | precinct='ASBURY PARK CITY'", "scan> Atlantic | DEMOCRAT | votes=2596 | precinct='ABSECON CITY'"];

let state = {
  datasetKey: null,
  dataset: null,
  stepIndex: 0
};

const app = document.getElementById("app");
const chip = document.getElementById("chip");

function setChip(text) { chip.textContent = text; }

function fmtValue(value, unit) {
  if (unit === "%") return value.toFixed(1) + "%";
  if (unit === "votes") return value.toLocaleString();
  return value.toString();
}

function findMax(bars) {
  const vals = bars.map(b => b.value);
  return Math.max(...vals);
}

function renderWelcome() {
  setChip("Ready");
  app.innerHTML = `
    <section class="card">
      <div>
        <div class="h1">An introductory walkthrough of election data analysis</div>
        <p class="p">
          This program demonstrates a step-by-step election analysis in two modes:
          <b>real NJ public data</b> (transparent sources and some limitations) and
          <b>synthetic demo data</b> (to showcase additional methods like Benford + outlier detection).
        </p>

        <div class="stepper">
          <span class="step active">1. Choose dataset</span>
          <span class="step">2. Walkthrough</span>
          <span class="step">3. Summary</span>
        </div>

        <div class="actions">
          <button class="btn primary" onclick="renderDatasetChoice()">Start</button>
          <button class="btn secondary" onclick="renderAbout()">About</button>
        </div>
    </section>
      <hr style="
        border:none;
        border-top:1px solid var(--border);
        margin:26px 0 18px;
      ">
    <p class="p" style="font-size:13.5px;">
      Focus: introductory analysis, transparent assumptions, and clear visual explanations.
    </p>
  `;
}

function renderAbout() {
  setChip("About");
  app.innerHTML = `
    <section class="card">
      <div class="h2">About this software</div>
      <p class="p">
        This is a <b>static</b> web application. It runs by opening <code>index.html</code>.
        The goal is to present analysis like a piece of software, while still being easy for users to run.
      </p>
      <p class="p">
        The real dataset is from public sources. The synthetic dataset is generated for demonstration and includes injected anomalies.
      </p>
      <div class="actions">
        <button class="btn primary" onclick="renderDatasetChoice()">Choose dataset</button>
        <button class="btn secondary" onclick="renderWelcome()">Back</button>
      </div>
    </section>
  `;
}

function renderDatasetChoice() {
  setChip("Choose dataset");
  app.innerHTML = `
    <section class="card grid">
      <div>
        <div class="h2">Select a dataset</div>
        <p class="p">
          <b>Real NJ public data</b> focuses on county turnout and county comparisons (2020 General Election).
          <br/> <b>Synthetic demo data</b> enables extra methods like Benford’s Law and precinct-level outlier detection.
        </p>

        <div class="actions">
          <button class="btn primary" onclick="startLoading('real')">Real NJ Public Data</button>
          <button class="btn secondary" onclick="startLoading('synthetic')">Synthetic Demo Data</button>
          <button class="btn ghost" onclick="renderWelcome()">Cancel</button>
        </div>
      </div>

      <div class="sourcebox">
        <b>Real dataset sources</b><br/>
        MIT Election Data and Science Lab (2022), “U.S. President Precinct-Level Returns 2020” (Harvard Dataverse, V4).<br/>
        <a href="https://doi.org/10.7910/DVN/JXPREB" target="_blank" rel="noreferrer">doi:10.7910/DVN/JXPREB</a><br/><br/>
        NJ Division of Elections (2020), Official General Election Voter Turnout (County-level).<br/>
        <a href="https://www.nj.gov/state/elections/assets/pdf/election-results/2020/2020-official-general-voter-turnout.pdf" target="_blank" rel="noreferrer">PDF source</a>
      </div>
    </section>
  `;
}

function startLoading(key) {
  state.datasetKey = key;
  state.dataset = DATASETS[key];
  state.stepIndex = 0;

  setChip("Loading…");
  const isReal = key === "real";
  const lines = isReal ? SCAN_LINES_REAL : [
    "scan> generating synthetic precincts…",
    "scan> injecting anomalies for demonstration…",
    "scan> computing Benford distribution…",
    "scan> scoring LOF outliers…",
    "scan> preparing charts…"
  ];

  renderLoading(lines, () => renderStep(0));
}

function renderLoading(lines, done) {
  const total = 100;
  let pct = 0;
  let lineIndex = 0;

  app.innerHTML = `
    <section class="card loaderWrap">
      <div class="loaderTop">
        <div class="spinner"></div>
        <div>
          <div class="h2">Preparing analysis</div>
          <div class="p">Reading data, computing metrics, and building visuals…</div>
        </div>
        <div style="margin-left:auto; font-weight:800; color:var(--accent);" id="pct">0%</div>
      </div>

      <div class="progress"><div id="bar"></div></div>

      <div class="console" id="console">
        <div class="muted">console&gt; initializing…</div>
      </div>
    </section>
  `;

  const pctEl = document.getElementById("pct");
  const barEl = document.getElementById("bar");
  const con = document.getElementById("console");

  const timer = setInterval(() => {
    pct += 2 + Math.floor(Math.random()*4); // 2–5%
    if (pct > total) pct = total;

    pctEl.textContent = pct + "%";
    barEl.style.width = pct + "%";

    const line = lines[lineIndex % lines.length];
    lineIndex += 1;
    const div = document.createElement("div");
    div.textContent = line;
    con.appendChild(div);

    while (con.children.length > 12) con.removeChild(con.children[0]);

    if (pct >= total) {
      clearInterval(timer);
      setTimeout(() => {
        setChip("Walkthrough");
        done();
      }, 350);
    }
  }, 120);
}

function renderStep(idx) {
  state.stepIndex = idx;
  const ds = state.dataset;
  const step = ds.steps[idx];
  const isLast = idx === ds.steps.length - 1;

  const max = findMax(step.bars);
  const unit = step.unit;

  const barsHtml = step.bars.map(b => `
    <div class="barCol">
      <div class="bar" data-value="${b.value}" data-max="${max}"></div>
      <div class="barLbl">${b.label}</div>
      <div class="barVal">${fmtValue(b.value, unit)}</div>
    </div>
  `).join("");

  const stepDots = ds.steps.map((s, i) => `
    <span class="step ${i===idx ? "active" : ""}">${i+1}. ${s.title}</span>
  `).join("");

  const kpis = Object.entries(step.kpis || {}).map(([k,v]) => `
    <div class="kpi"><div class="t">${k}</div><div class="v">${v}</div><div class="s">computed</div></div>
  `).join("");

  const meta = ds.meta;
  const metaLine = `${meta.year} • ${meta.election}`;

  app.innerHTML = `
    <section class="card">
      <div class="h2">${meta.label}</div>
      <div class="p">${metaLine}</div>

      <div class="stepper">${stepDots}</div>

      <div style="margin-top:14px;" class="grid">
        <div class="chartWrap">
          <div class="h2" style="margin-bottom:6px;">${step.title}</div>
          <div class="p">${step.subtitle}</div>

          <div class="chart" aria-label="bar chart">
            ${barsHtml}
          </div>
          <div class="p" style="margin-top:10px;">${step.summary}</div>
        </div>

        <div>
          <div class="sourcebox">
            <b>Dataset metadata</b><br/>
            <div style="margin-top:8px;">
              <span class="muted">Year:</span> <b>${meta.year}</b><br/>
              <span class="muted">Election:</span> <b>${meta.election}</b>
            </div>
            <div style="margin-top:10px;">
              <b>Sources</b><br/>
              ${meta.sources.map(s => s.url ? `<a href="${s.url}" target="_blank" rel="noreferrer">${s.title}</a>` : `<span>${s.title}</span>`).join("<br/><br/>")}
            </div>
          </div>

          <div class="kpis">${kpis}</div>
        </div>
      </div>

      <div class="actions">
        <button class="btn secondary" onclick="goBack()">Back</button>
        <button class="btn primary" onclick="goNext()">${isLast ? "Finish" : "Continue"}</button>
      </div>
    </section>
  `;

  animateBars();
}

function animateBars() {
  const bars = document.querySelectorAll(".bar");
  const isOutliers = state.datasetKey === "synthetic" &&
                     state.dataset.steps[state.stepIndex].id === "outliers";

  bars.forEach(bar => {
    const value = parseFloat(bar.dataset.value);
    const max = parseFloat(bar.dataset.max);

    // NORMAL charts vs LOF chart
    const maxHeight = isOutliers ? 205 : 230;

    const h = Math.max(8, (value / max) * maxHeight);
    requestAnimationFrame(() => {
      bar.style.height = h + "px";
    });
  });
}

function goNext() {
  const ds = state.dataset;
  if (state.stepIndex < ds.steps.length - 1) {
    renderStep(state.stepIndex + 1);
  } else {
    renderFinal();
  }
}

function goBack() {
  if (state.stepIndex > 0) renderStep(state.stepIndex - 1);
  else renderDatasetChoice();
}

function renderFinal() {
  setChip("Summary");
  const ds = state.dataset;
  const meta = ds.meta;

  const topTurnout = ds.steps[0].bars[0];
  let finalNote = "";
  if (state.datasetKey === "real") {
    finalNote = ds.benford_note;
  } else {
    const outStep = ds.steps.find(s => s.id === "outliers");
    const topOut = outStep ? outStep.bars[0] : null;
    finalNote = topOut ? `Most unusual flagged precinct (demo): <b>${topOut.label}</b> (LOF score ${topOut.value}).` : "";
  }

  app.innerHTML = `
    <section class="card grid">
      <div>
        <div class="h1">Summary</div>
        <p class="p">
          Dataset: <b>${meta.label}</b><br/>
          Year/Election: <b>${meta.year} • ${meta.election}</b>
        </p>

        <div class="sourcebox">
          <b>Key takeaways</b><br/>
          • Highest turnout (from this walkthrough): <b>${topTurnout.label}</b> (${topTurnout.value}%)<br/>
          • ${finalNote}
        </div>

        <div class="actions">
          <button class="btn primary" onclick="renderDatasetChoice()">Run again</button>
          <button class="btn secondary" onclick="renderWelcome()">Home</button>
        </div>
      </div>

      <div class="sourcebox">
        <b>Method note</b><br/>
        This program is designed for educational exploration. Charts summarize and compare patterns.
        Outlier flags (synthetic mode) are prompts for investigation, not conclusions.
        <div style="margin-top:10px;">
          ${state.datasetKey === "real" ? `<span style="color:var(--warn); font-weight:700;">Benford note:</span> ${ds.benford_note}` : ""}
        </div>
      </div>
    </section>
  `;
}

renderWelcome();
